### ISSUE TITLE
IOS not working

### ISSUE THREAD

**Issue by liho00** [reyhankaplan/react-native-ringer-mode#3]
ringerMode is undefined on IOS 15

**Comment by kutsan** [comment]
Because of the limitations of Apple, as far as I know it's not possible to control ringer mode on iOS devices, so which makes this library an Android-only one. I think this should have mentioned in the README better.

**Comment by liho00** [comment]
How about accessing the silent mode state & do not disturb state, without controlling these mode?

One of the use case of accessing these state is notify user he's in silent mode probably not able to get notified when notification comes in.

**Comment by kutsan** [comment]
@liho00 Still, as far as I know there is no such API to get status of whether or not device in its silent mode. I guess Apple restricts developers to access it because of privacy concerns. But I think it's possible to access focus feature of iOS devices and this can be implemented.

**Comment by reyhankaplan** [comment]
Hi @liho00, as @kutsan said I don't know a way to support iOS at the moment. If you find a way to do it, we are open to PRs. I'll keep an eye on this topic, thanks!
